#FROM node:alpine
#ENV PATH node_modules/.bin:$PATH
#COPY package.json ./
#RUN npm install
#RUN npm install -g @angular/cli
#COPY . .
#CMD npm build-prod

#FROM nginx:alpine
#COPY src /usr/share/nginx/html/
#COPY nginx.conf /etc/nginx/conf.d/default.conf
